### ISSUE TITLE
stemmer is not defined error

### ISSUE THREAD

**Issue by Fatima-200159617** [marcocor/wikipedia-idf#1]
Hi marco,

Thanks for the source code. I followed your suggested pipeline, I processed the Wikipedia dump using the WikiExtractor, but when it comes to the wikipediaidf.py, I am getting an error at line 82 saying that stemmer is not defined. I am not able to figure out what is causing this error. I would appreciate if you could help.

**Comment by maulidaannisa** [comment]
Hi, same issue here. Do you find the solution?

**Comment by marcocor** [comment]
Hi @Fatima-200159617 and @maulidaannisa. I have fixed the bug and I believe the code should be working now.
