### ISSUE TITLE
Can anyone please share the IDF value file if they have already computed it over the wikipedia dump

### ISSUE THREAD

**Issue by vikas95** [marcocor/wikipedia-idf#3]
Hi,

Thanks for sharing the steps to compute and save the IDF values. 
I wanted to ask if you have a saved copy containing the IDF values of terms in English. It would be very helpful if you (or anyone) can share the computed IDF values.  I am hoping to save time by not download the wikipedia dump and running the same codes. 

Thanks.

**Comment by marcocor** [comment]
Hi @vikas95, unfortunately I don't have the file already computed, but I'd be glad to add it to this repository were you to generate it.
